name: Build and Publish to Docker Hub
on:
  release:
    types: [published]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image (latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eriknovak/infominer:latest
     - name: Build Docker Image (current version)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eriknovak/infominer:${{ github.event.release.tag_name }}
